import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";
import "@code-hike/mdx/dist/index.css";
import { Inter, Roboto_Mono, Lexend_Deca } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const lexend = Lexend_Deca({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${roboto_mono.variable} ${lexend.variable} container max-w-5xl justify-between pl-16 pr-8 pt-6`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div>
            <Header />
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
